config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'page#home'
  get 'about' , to:'page#about'
  resources :articles 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article< ApplicationRecord
validates :title , presence: true , length: {minimum: 5, maximum: 100}
validates :descrption , presence: true , length: {minimum: 15, maximum: 1000}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

before_action :set_article, only: [:show , :edit , :update , :destroy]

	def show
	end

	def index
		@articles = Article.all
	end

 	def new
 		@article = Article.new
 	end

 	def edit 
 	end


 	def create
 		@article = Article.new(article_params)
 		if @article.save
 			flash[:notice] = "Article has been successfully saved"
 		redirect_to article_path(@article)
 		else
 			render 'new'
 	end
    end
 	

 	def update
       if @article.update(article_params)
       flash[:notice] = "Articles are successfully updated"
       else
       render 'edit'
       end
 	end
 	def destroy
 		@article.destroy
 		#flash[:notice] = "Article was successfully destroyed".
 		redirect_to articles_path
 	end
   
    private
    
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
    	params.require(:article).permit(:title , :descrption)
    end


end

app/controllers/page_controller.rb
class PageController < ApplicationController

	def home
	end

	def about
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/masster_helper.rb
module MassterHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %> 
<h2> The following errors prevented the article from being saved </h2>
<ul>
<% @article.errors.full_messages.each do |msg| %>
	
	<li><%= msg %></li>

<% end %>
</ul>
<% end %>

<%= form_with(model: @article, local: true) do |f| %>

<p>
	<%= f.label :title %> <br/>
	<%= f.text_field :title %>
</p>

<p> <%= f.label :descrption%> <br/>
	<%= f.text_area :descrption%>
</p>

<p> <%= f.submit %></p>
	
<% end %>

app/views/articles/edit.html.erb
<h1> Edit new article </h1>
<%= render 'form'%>


<%= link_to "Return to listing", articles_path %>
<%= button_to "Destroy", article_path(@article), method: :delete, data: { confirm: "Are you sure" } %>

app/views/articles/index.html.erb
<h1> Articles listing page</h1>

<table>
<thead>
	<tr>
	<th> Title </th> <th> Descption </th> <th colspan="3"> Action </th>
	</tr>
</thead>

<tbody>
	<% @articles.each do |article| %>
	 <tr>
		<td><%= article.title %></td>
		<td><%= article.descrption %></td>
		<td><%= link_to "Show", article %> </td>
		<td><%= link_to "Edit", edit_article_path(article) %> </td>
		<td><%= button_to "Destroy", article, method: :delete, :confirm => "Are you sure?" %> </td>
	 </tr>
	<% end %>
</tbody>
</table>
<p>
<td><%= link_to "Create new article", new_article_path %> </td>
</p>

app/views/articles/new.html.erb
<h1> Create a new article </h1>
<%= render 'form' %>

<%= link_to "Return to listing", articles_path %>

app/views/articles/show.html.erb
<h1> showing the articles details</h1>

<p> <strong> Title : </strong> <%=@article.title%> </p>
<p> <strong>Descrption :  </strong><%=@article.descrption%> </p>



<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to "Return to listing", articles_path %>  |
<%= button_to 'Destroy', @article, method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } } %> 

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg| %>
    <%= msg %>
    <% end %>

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/page/about.html.erb
<h1> This is the about page </h1>
<%= link_to "Return to listing", articles_path %> | 
<%= link_to "home page", root_path %>

app/views/page/home.html.erb
<h1> Welcome to rails </h1>
<%= link_to "Return to listing", articles_path %> | 
<%= link_to "about page", about_path %>